# Generated by Django 3.1.3 on 2026-01-07 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=50)),
                ('category', models.CharField(default='', max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('image', models.ImageField(default='', upload_to='home/images')),
                ('slug', models.CharField(default='', max_length=1000)),
                ('sellername', models.CharField(default='', max_length=100)),
                ('pickuplocation', models.CharField(default='', max_length=1000)),
                ('college', models.CharField(default='All Colleges', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(max_length=50000)),
                ('name', models.CharField(max_length=900)),
                ('email', models.CharField(max_length=1101)),
                ('address', models.CharField(max_length=1101)),
                ('city', models.CharField(max_length=1101)),
                ('state', models.CharField(max_length=1101)),
                ('zip_code', models.CharField(max_length=1011)),
                ('phone', models.CharField(default='', max_length=1011)),
            ],
        ),
        migrations.CreateModel(
            name='TrackUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(default='', max_length=900)),
                ('update', models.CharField(default='', max_length=9000)),
                ('daysleft', models.CharField(default='', max_length=9000)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=100)),
                ('receiver', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.books')),
            ],
        ),
    ]
