# Generated by Django 3.1.3 on 2026-01-08 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=50)),
                ('category', models.CharField(default='', max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('image', models.ImageField(default='', upload_to='home/images')),
                ('slug', models.CharField(default='', max_length=1000)),
                ('sellername', models.CharField(default='', max_length=100)),
                ('pickuplocation', models.CharField(default='', max_length=1000)),
                ('college', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='chat',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.book'),
        ),
        migrations.DeleteModel(
            name='books',
        ),
    ]
